server:
  port: ${PORT:8080}

eureka:instance:
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 3

  client:
    serviceUrl:
      # defaultZone: http://user:password@localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: hello-service

spring:
  application:
    name: hello-service

management:
  security:
    enabled: false


